In [1]:
with open('inputs/4.txt', 'r') as file:
    inp = file.read()[:-1]

In [2]:
import numpy as np

In [3]:
inp2 = inp.split("\n\n")
draw = [int(i) for i in inp2[0].split(",")]
print(draw)

boards = [i.split("\n") for i in inp2[1:]]

new_bs = []
for b in boards:
    new_b = []
    for l in b:
        new_b.append([int(n) for n in l.split()])
    new_bs.append(new_b)

draw = np.array(draw)
new_bs = np.array(new_bs)
print(draw, new_bs)

[30, 35, 8, 2, 39, 37, 72, 7, 81, 41, 25, 46, 56, 18, 89, 70, 0, 15, 84, 75, 88, 67, 42, 44, 94, 71, 79, 65, 58, 52, 96, 83, 54, 29, 14, 95, 66, 61, 97, 68, 57, 90, 55, 32, 17, 47, 20, 98, 1, 69, 63, 62, 31, 86, 77, 85, 87, 93, 26, 40, 24, 19, 48, 76, 73, 49, 34, 45, 82, 22, 80, 78, 23, 6, 59, 91, 64, 43, 21, 51, 13, 3, 53, 99, 4, 28, 33, 74, 12, 9, 36, 50, 60, 11, 27, 10, 5, 16, 92, 38]
[30 35  8  2 39 37 72  7 81 41 25 46 56 18 89 70  0 15 84 75 88 67 42 44
 94 71 79 65 58 52 96 83 54 29 14 95 66 61 97 68 57 90 55 32 17 47 20 98
  1 69 63 62 31 86 77 85 87 93 26 40 24 19 48 76 73 49 34 45 82 22 80 78
 23  6 59 91 64 43 21 51 13  3 53 99  4 28 33 74 12  9 36 50 60 11 27 10
  5 16 92 38] [[[94 97 41 22 48]
  [21 47 72 23 26]
  [12 81 86 24 91]
  [71 78 90 59 54]
  [92 63 68 65  1]]

 [[75 62 66 74 37]
  [14 79 35 96 30]
  [33 25 29 57  6]
  [60 93 17 55 53]
  [65 16 59 40 27]]

 [[26 60 95 24 78]
  [55 12 22 68 43]
  [67 48 85 66 36]
  [29 80 52  3 56]
  [11 59 41 15 18]]

 ...

 [[ 0 

In [4]:
# 1
full = np.concatenate((new_bs[:,None,:,:], np.zeros(new_bs.shape)[:,None,:,:]), axis=1)
print(full.shape)
for i in draw:
    full[:,1,:,:][full[:,0,:,:] == i] = 1
    if np.any(np.sum(full[:,1,:,:], axis=1) == 5):
        #print(full)
        winner = np.any(np.sum(full[:,1,:,:], axis=1) == 5, axis=1)
        print(int(np.sum(full[winner,0,:,:][full[winner,1,:,:] == 0]) * i))
        break
    if np.any(np.sum(full[:,1,:,:], axis=2) == 5):
        #print(full)
        winner = np.any(np.sum(full[:,1,:,:], axis=2) == 5, axis=1)
        print(int(np.sum(full[winner,0,:,:][full[winner,1,:,:] == 0]) * i))
        break

(100, 2, 5, 5)
54275


In [5]:
# 2
full = np.concatenate((new_bs[:,None,:,:], np.zeros(new_bs.shape)[:,None,:,:]), axis=1)

for i in draw:
    full[:,1,:,:][full[:,0,:,:] == i] = 1
    if np.any(np.sum(full[:,1,:,:], axis=1) == 5):
        if full.shape[0] == 1:
            print(int(np.sum(full[0,0,:,:][full[0,1,:,:] == 0]) * i))
            break
        winner = np.any(np.sum(full[:,1,:,:], axis=1) == 5, axis=1)
        full = full[np.logical_not(winner)]
        
    if np.any(np.sum(full[:,1,:,:], axis=2) == 5):
        if full.shape[0] == 1:
            print(int(np.sum(full[0,0,:,:][full[0,1,:,:] == 0]) * i))
            break
        winner = np.any(np.sum(full[:,1,:,:], axis=2) == 5, axis=1)
        full = full[np.logical_not(winner)]       

13158
